### ISSUE TITLE
 v4.1.0 reported as malicious by VirusTotal

### ISSUE THREAD

**Issue by thegreatprophetzarquon** [DarkLord76865/Full-Tilt-Pinball#1]
The latest build's executable flags as malicious "by 13 vendors," as linked on the release page. I'm assuming all is well given that this was just built by github actions, but given that the results are prominently linked right on the release page, this might put off some folks if the results remain linked or aren't noted on the release page.

**Comment by amamic1803** [comment]
Hi,
thanks for bringing this up. I did notice that some VT scanners flagged it as malicious, but I guess I thought no one will ever be interested in downloading it 🥲. I added a message to release like you suggested. Executable is 100% safe as it only contains Python code and full tilt boards that are also provided under release and are not themselves flagged as malicious. I guess you probably found my repo while searching for Space Cadet board, in that case I suggest to check out the improved version in the repository linked in README, as the version here is the original win 95 version.
Regards
